input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["comteco-logs"]
    group_id => "logstash-comteco"
    codec => "json"
    auto_offset_reset => "latest"
  }
}

filter {
  mutate {
    add_field => { "capa_procesamiento" => "activa" }
  }

    grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_fecha} %{NUMBER:thread_id} \[%{DATA:log_nivel}\] \[%{DATA:log_codigo}\] \[%{DATA:log_componente}\] %{GREEDYDATA:log_detalle}"
    }
  }
}

output {
  stdout {
    codec => line { format => "%{log_fecha} | %{[fields][servidor]} | %{[fields][servicio]} | %{log_nivel} | %{log_codigo} | %{log_componente} | %{log_detalle}" }
  }

  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "comteco-logs-procesados"
    codec => json
  }
}