filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/messages
    - /var/log/secure
  fields:
    servidor: NOMBRE_SERVIDOR
    servicio: linux
    empresa: comteco

output.kafka:
  hosts: ["IP_KAFKA:29092"]
  topic: "comteco-logs"
  required_acks: 1
  compression: gzip

logging.level: info